// รายการ error code ทั้งหมด: HTTP status + ข้อความภาษาไทย (ตาม http-api-spec ข้อ 5)
// {n} ในข้อความแทนด้วย params.n ตอนสร้าง AppError

export const ERROR_CODES = {
  VALIDATION_ERROR: { status: 400, message: 'ข้อมูลไม่ถูกต้อง' },
  INVALID_FILE: { status: 400, message: 'ไฟล์ต้องเป็นรูป jpg, png หรือ webp ขนาดไม่เกิน 2 MB' },
  INVALID_DUE_AT: { status: 400, message: 'เวลาคืนไม่ถูกต้อง' },
  INVALID_TIME_RANGE: { status: 400, message: 'ช่วงเวลาไม่ถูกต้อง' },
  RESERVATION_TOO_FAR_AHEAD: { status: 400, message: 'จองล่วงหน้าได้ไม่เกิน {n} วัน' },
  CURRENT_PASSWORD_INCORRECT: { status: 400, message: 'รหัสผ่านปัจจุบันไม่ถูกต้อง' },
  UNKNOWN_SETTING: { status: 400, message: 'ไม่มีค่าตั้งค่านี้ในระบบ' },
  UNAUTHORIZED: { status: 401, message: 'กรุณาเข้าสู่ระบบใหม่' },
  INVALID_CREDENTIALS: { status: 401, message: 'อีเมลหรือรหัสผ่านไม่ถูกต้อง' },
  ACCOUNT_SUSPENDED: { status: 403, message: 'บัญชีนี้ถูกระงับ กรุณาติดต่อผู้ดูแลระบบ' },
  FORBIDDEN: { status: 403, message: 'คุณไม่มีสิทธิ์ทำรายการนี้' },
  NOT_FOUND: { status: 404, message: 'ไม่พบหน้าที่เรียก' },
  USER_NOT_FOUND: { status: 404, message: 'ไม่พบผู้ใช้' },
  BRAND_NOT_FOUND: { status: 404, message: 'ไม่พบยี่ห้อ' },
  MODEL_NOT_FOUND: { status: 404, message: 'ไม่พบรุ่น' },
  NOTEBOOK_NOT_FOUND: { status: 404, message: 'ไม่พบโน๊ตบุ๊ค' },
  LOAN_NOT_FOUND: { status: 404, message: 'ไม่พบรายการยืม' },
  RESERVATION_NOT_FOUND: { status: 404, message: 'ไม่พบการจอง' },
  NOTIFICATION_NOT_FOUND: { status: 404, message: 'ไม่พบการแจ้งเตือน' },
  AUDIT_LOG_NOT_FOUND: { status: 404, message: 'ไม่พบ Audit Log' },
  EMAIL_TAKEN: { status: 409, message: 'อีเมลนี้ถูกใช้แล้ว' },
  MEMBER_CODE_TAKEN: { status: 409, message: 'รหัสสมาชิกนี้ถูกใช้แล้ว' },
  BRAND_NAME_TAKEN: { status: 409, message: 'มียี่ห้อนี้อยู่แล้ว' },
  MODEL_NAME_TAKEN: { status: 409, message: 'มีรุ่นนี้ในยี่ห้อนี้อยู่แล้ว' },
  ASSET_CODE_TAKEN: { status: 409, message: 'รหัสครุภัณฑ์นี้ถูกใช้แล้ว' },
  SERIAL_NUMBER_TAKEN: { status: 409, message: 'Serial number นี้ถูกใช้แล้ว' },
  BRAND_IN_USE: { status: 409, message: 'ลบไม่ได้ ยังมีรุ่นที่ใช้ยี่ห้อนี้' },
  MODEL_IN_USE: { status: 409, message: 'ลบไม่ได้ ยังมีเครื่องที่ใช้รุ่นนี้' },
  NOTEBOOK_HAS_COMMITMENTS: { status: 409, message: 'ทำรายการไม่ได้ เครื่องนี้มีการยืมหรือการจองค้างอยู่' },
  NOTEBOOK_NOT_AVAILABLE: { status: 409, message: 'เครื่องนี้ไม่พร้อมให้ยืม' },
  NOTEBOOK_ALREADY_BORROWED: { status: 409, message: 'เครื่องนี้ถูกยืมอยู่' },
  NOTEBOOK_NOT_RETURNED_YET: { status: 409, message: 'ผู้ยืมคนก่อนยังไม่ได้คืนเครื่อง กรุณาติดต่อผู้ดูแลระบบ' },
  RESERVATION_CONFLICT: { status: 409, message: 'ช่วงเวลานี้มีผู้จองไว้แล้ว' },
  OWN_RESERVATION_OVERLAP: {
    status: 409,
    message: 'คุณมีการจองเครื่องนี้ในช่วงเวลานี้ กรุณารับเครื่องจากการจองหรือยกเลิกการจองก่อน',
  },
  LOAN_CONFLICT: { status: 409, message: 'ช่วงเวลานี้เครื่องถูกยืมอยู่' },
  EXTEND_CONFLICT_RESERVATION: { status: 409, message: 'ต่อเวลาไม่ได้ มีผู้จองเครื่องต่อจากคุณ' },
  LOAN_NOT_ACTIVE: { status: 409, message: 'รายการยืมนี้ไม่อยู่ในสถานะที่ทำรายการได้' },
  LOAN_OVERDUE_CANNOT_EXTEND: { status: 409, message: 'เกินกำหนดคืนแล้ว ไม่สามารถต่อเวลาได้' },
  RETURN_ALREADY_REQUESTED: { status: 409, message: 'คุณกดคืนเครื่องนี้แล้ว รอผู้ดูแลยืนยัน' },
  LOAN_ALREADY_RETURNED: { status: 409, message: 'รายการนี้รับคืนเรียบร้อยแล้ว' },
  LOAN_CANCELLED: { status: 409, message: 'รายการนี้ถูกยกเลิกแล้ว' },
  LOAN_CANNOT_CANCEL: { status: 409, message: 'ยกเลิกไม่ได้ รายการนี้รับคืนแล้วหรือถูกยกเลิกไปแล้ว' },
  LOAN_STATE_CHANGED: { status: 409, message: 'สถานะรายการเปลี่ยนไปแล้ว กรุณาโหลดหน้าใหม่' },
  RESERVATION_NOT_STARTED: { status: 409, message: 'ยังไม่ถึงเวลารับเครื่อง' },
  RESERVATION_EXPIRED: { status: 409, message: 'การจองหมดอายุแล้ว' },
  RESERVATION_CANCELLED: { status: 409, message: 'การจองนี้ถูกยกเลิกแล้ว' },
  RESERVATION_ALREADY_PICKED_UP: { status: 409, message: 'รับเครื่องตามการจองนี้แล้ว' },
  RESERVATION_CANNOT_CANCEL: { status: 409, message: 'ยกเลิกการจองนี้ไม่ได้' },
  CANNOT_MODIFY_SELF: { status: 409, message: 'ไม่สามารถทำรายการนี้กับบัญชีของตัวเองได้' },
  LAST_ADMIN: { status: 409, message: 'ต้องมีผู้ดูแลระบบที่ใช้งานได้อย่างน้อย 1 คน' },
  USER_HAS_ACTIVE_LOANS: { status: 409, message: 'ลบไม่ได้ ผู้ใช้นี้ยังมีเครื่องที่ยังไม่คืน' },
  REFERENCE_NOT_FOUND: { status: 409, message: 'ข้อมูลที่อ้างถึงไม่มีอยู่ในระบบ' },
  RESOURCE_IN_USE: { status: 409, message: 'ข้อมูลนี้ถูกใช้งานอยู่' },
  LOAN_LIMIT_REACHED: { status: 422, message: 'คุณยืมครบจำนวนสูงสุดแล้ว กรุณาคืนเครื่องก่อน' },
  LOAN_DURATION_EXCEEDED: { status: 422, message: 'เวลายืมรวมเกิน {n} ชั่วโมง' },
  INTERNAL_ERROR: { status: 500, message: 'ระบบขัดข้อง กรุณาลองใหม่อีกครั้ง' },
};
