-- =====================================================================
-- User Management System - MariaDB 10.4+ / MySQL 8 schema (3NF), XAMPP compatible.
-- Idempotent. Applied by `npm run db:init` (which creates the database first).
-- =====================================================================
SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS user_statuses (
  id          SMALLINT     NOT NULL PRIMARY KEY,
  code        VARCHAR(20)  NOT NULL UNIQUE,
  description VARCHAR(100) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS roles (
  id          SMALLINT     NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name        VARCHAR(50)  NOT NULL UNIQUE,
  description VARCHAR(255) NOT NULL DEFAULT ''
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS permissions (
  id          SMALLINT     NOT NULL AUTO_INCREMENT PRIMARY KEY,
  code        VARCHAR(50)  NOT NULL UNIQUE,         -- e.g. user:read
  description VARCHAR(255) NOT NULL DEFAULT ''
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS role_permissions (
  role_id       SMALLINT NOT NULL,
  permission_id SMALLINT NOT NULL,
  PRIMARY KEY (role_id, permission_id),
  FOREIGN KEY (role_id)       REFERENCES roles(id)       ON DELETE CASCADE,
  FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Timestamps are stored in UTC (the app sets the session time_zone to +00:00).
CREATE TABLE IF NOT EXISTS users (
  id                  CHAR(36)     NOT NULL PRIMARY KEY,   -- UUID generated by the app
  username            VARCHAR(50)  NOT NULL,
  email               VARCHAR(255) NOT NULL,
  password_hash       VARCHAR(100) NOT NULL,               -- bcrypt hash only, never plain text
  status_id           SMALLINT     NOT NULL DEFAULT 1,
  token_version       INT          NOT NULL DEFAULT 0,     -- bump to invalidate every issued JWT
  failed_login_count  SMALLINT     NOT NULL DEFAULT 0,
  locked_until        TIMESTAMP NULL DEFAULT NULL,
  last_login_at       TIMESTAMP NULL DEFAULT NULL,
  password_changed_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by          CHAR(36)     NULL,
  updated_by          CHAR(36)     NULL,
  deleted_at          TIMESTAMP NULL DEFAULT NULL,         -- soft delete
  -- MariaDB has no partial unique indexes: these are NULL once soft-deleted and UNIQUE
  -- ignores NULLs, so a deleted username/email can be reused.
  live_username VARCHAR(50)  AS (IF(deleted_at IS NULL, username, NULL)) PERSISTENT,
  live_email    VARCHAR(255) AS (IF(deleted_at IS NULL, email, NULL))    PERSISTENT,
  UNIQUE KEY ux_users_username (live_username),
  UNIQUE KEY ux_users_email    (live_email),
  KEY ix_users_status (status_id),
  KEY ix_users_created_at (created_at),
  CONSTRAINT ck_users_username_format CHECK (username COLLATE utf8mb4_bin REGEXP '^[a-z0-9._-]{3,50}$'),
  CONSTRAINT ck_users_email_lower     CHECK (email COLLATE utf8mb4_bin = LOWER(email)),
  CONSTRAINT ck_users_hash_bcrypt     CHECK (password_hash REGEXP '^[$]2[aby][$][0-9]{2}[$]'),
  FOREIGN KEY (status_id)  REFERENCES user_statuses(id),
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS user_profiles (
  user_id    CHAR(36)     NOT NULL PRIMARY KEY,
  first_name VARCHAR(100),
  last_name  VARCHAR(100),
  phone      VARCHAR(30),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS user_roles (
  user_id     CHAR(36)  NOT NULL,
  role_id     SMALLINT  NOT NULL,
  assigned_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, role_id),
  KEY ix_user_roles_role (role_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE RESTRICT
) ENGINE=InnoDB;

-- JWTs revoked by logout. Rows may be purged once expires_at has passed.
CREATE TABLE IF NOT EXISTS revoked_tokens (
  jti        CHAR(36)  NOT NULL PRIMARY KEY,
  user_id    CHAR(36)  NOT NULL,
  expires_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  revoked_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY ix_revoked_tokens_expires (expires_at),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Append-only audit trail. details never contains passwords or hashes.
CREATE TABLE IF NOT EXISTS audit_logs (
  id            BIGINT      NOT NULL AUTO_INCREMENT PRIMARY KEY,
  actor_user_id CHAR(36)    NULL,
  action        VARCHAR(50) NOT NULL,                -- USER_CREATED, LOGIN_FAILED, ...
  entity_type   VARCHAR(50) NOT NULL,                -- user, auth, ...
  entity_id     VARCHAR(64),
  details       LONGTEXT    NOT NULL,                -- JSON document
  ip_address    VARCHAR(45),
  user_agent    VARCHAR(255),
  created_at    TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY ix_audit_actor   (actor_user_id, created_at),
  KEY ix_audit_entity  (entity_type, entity_id),
  KEY ix_audit_action  (action, created_at),
  KEY ix_audit_created (created_at),
  CONSTRAINT ck_audit_details_json CHECK (JSON_VALID(details)),
  FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;
